// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_math_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_math_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_math_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_math_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_math_2eproto;
class MathAddReqeust;
struct MathAddReqeustDefaultTypeInternal;
extern MathAddReqeustDefaultTypeInternal _MathAddReqeust_default_instance_;
class MathAddResponse;
struct MathAddResponseDefaultTypeInternal;
extern MathAddResponseDefaultTypeInternal _MathAddResponse_default_instance_;
class MathSubReqeust;
struct MathSubReqeustDefaultTypeInternal;
extern MathSubReqeustDefaultTypeInternal _MathSubReqeust_default_instance_;
class MathSubResponse;
struct MathSubResponseDefaultTypeInternal;
extern MathSubResponseDefaultTypeInternal _MathSubResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MathAddReqeust* Arena::CreateMaybeMessage<::MathAddReqeust>(Arena*);
template<> ::MathAddResponse* Arena::CreateMaybeMessage<::MathAddResponse>(Arena*);
template<> ::MathSubReqeust* Arena::CreateMaybeMessage<::MathSubReqeust>(Arena*);
template<> ::MathSubResponse* Arena::CreateMaybeMessage<::MathSubResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MathAddReqeust final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MathAddReqeust) */ {
 public:
  inline MathAddReqeust() : MathAddReqeust(nullptr) {}
  ~MathAddReqeust() override;
  explicit PROTOBUF_CONSTEXPR MathAddReqeust(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathAddReqeust(const MathAddReqeust& from);
  MathAddReqeust(MathAddReqeust&& from) noexcept
    : MathAddReqeust() {
    *this = ::std::move(from);
  }

  inline MathAddReqeust& operator=(const MathAddReqeust& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathAddReqeust& operator=(MathAddReqeust&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathAddReqeust& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathAddReqeust* internal_default_instance() {
    return reinterpret_cast<const MathAddReqeust*>(
               &_MathAddReqeust_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MathAddReqeust& a, MathAddReqeust& b) {
    a.Swap(&b);
  }
  inline void Swap(MathAddReqeust* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathAddReqeust* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathAddReqeust* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathAddReqeust>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathAddReqeust& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathAddReqeust& from) {
    MathAddReqeust::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathAddReqeust* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MathAddReqeust";
  }
  protected:
  explicit MathAddReqeust(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAugendFieldNumber = 1,
    kAddendFieldNumber = 2,
  };
  // int64 augend = 1;
  void clear_augend();
  int64_t augend() const;
  void set_augend(int64_t value);
  private:
  int64_t _internal_augend() const;
  void _internal_set_augend(int64_t value);
  public:

  // int64 addend = 2;
  void clear_addend();
  int64_t addend() const;
  void set_addend(int64_t value);
  private:
  int64_t _internal_addend() const;
  void _internal_set_addend(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:MathAddReqeust)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t augend_;
    int64_t addend_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// -------------------------------------------------------------------

class MathAddResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MathAddResponse) */ {
 public:
  inline MathAddResponse() : MathAddResponse(nullptr) {}
  ~MathAddResponse() override;
  explicit PROTOBUF_CONSTEXPR MathAddResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathAddResponse(const MathAddResponse& from);
  MathAddResponse(MathAddResponse&& from) noexcept
    : MathAddResponse() {
    *this = ::std::move(from);
  }

  inline MathAddResponse& operator=(const MathAddResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathAddResponse& operator=(MathAddResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathAddResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathAddResponse* internal_default_instance() {
    return reinterpret_cast<const MathAddResponse*>(
               &_MathAddResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MathAddResponse& a, MathAddResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MathAddResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathAddResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathAddResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathAddResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathAddResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathAddResponse& from) {
    MathAddResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathAddResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MathAddResponse";
  }
  protected:
  explicit MathAddResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // int64 result = 1;
  void clear_result();
  int64_t result() const;
  void set_result(int64_t value);
  private:
  int64_t _internal_result() const;
  void _internal_set_result(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:MathAddResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// -------------------------------------------------------------------

class MathSubReqeust final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MathSubReqeust) */ {
 public:
  inline MathSubReqeust() : MathSubReqeust(nullptr) {}
  ~MathSubReqeust() override;
  explicit PROTOBUF_CONSTEXPR MathSubReqeust(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathSubReqeust(const MathSubReqeust& from);
  MathSubReqeust(MathSubReqeust&& from) noexcept
    : MathSubReqeust() {
    *this = ::std::move(from);
  }

  inline MathSubReqeust& operator=(const MathSubReqeust& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathSubReqeust& operator=(MathSubReqeust&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathSubReqeust& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathSubReqeust* internal_default_instance() {
    return reinterpret_cast<const MathSubReqeust*>(
               &_MathSubReqeust_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MathSubReqeust& a, MathSubReqeust& b) {
    a.Swap(&b);
  }
  inline void Swap(MathSubReqeust* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathSubReqeust* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathSubReqeust* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathSubReqeust>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathSubReqeust& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathSubReqeust& from) {
    MathSubReqeust::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathSubReqeust* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MathSubReqeust";
  }
  protected:
  explicit MathSubReqeust(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMinuendFieldNumber = 1,
    kSubtrahendFieldNumber = 2,
  };
  // int64 minuend = 1;
  void clear_minuend();
  int64_t minuend() const;
  void set_minuend(int64_t value);
  private:
  int64_t _internal_minuend() const;
  void _internal_set_minuend(int64_t value);
  public:

  // int64 subtrahend = 2;
  void clear_subtrahend();
  int64_t subtrahend() const;
  void set_subtrahend(int64_t value);
  private:
  int64_t _internal_subtrahend() const;
  void _internal_set_subtrahend(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:MathSubReqeust)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t minuend_;
    int64_t subtrahend_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// -------------------------------------------------------------------

class MathSubResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MathSubResponse) */ {
 public:
  inline MathSubResponse() : MathSubResponse(nullptr) {}
  ~MathSubResponse() override;
  explicit PROTOBUF_CONSTEXPR MathSubResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathSubResponse(const MathSubResponse& from);
  MathSubResponse(MathSubResponse&& from) noexcept
    : MathSubResponse() {
    *this = ::std::move(from);
  }

  inline MathSubResponse& operator=(const MathSubResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathSubResponse& operator=(MathSubResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathSubResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathSubResponse* internal_default_instance() {
    return reinterpret_cast<const MathSubResponse*>(
               &_MathSubResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MathSubResponse& a, MathSubResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MathSubResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathSubResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathSubResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathSubResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathSubResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathSubResponse& from) {
    MathSubResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathSubResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MathSubResponse";
  }
  protected:
  explicit MathSubResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // int64 result = 1;
  void clear_result();
  int64_t result() const;
  void set_result(int64_t value);
  private:
  int64_t _internal_result() const;
  void _internal_set_result(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:MathSubResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MathAddReqeust

// int64 augend = 1;
inline void MathAddReqeust::clear_augend() {
  _impl_.augend_ = int64_t{0};
}
inline int64_t MathAddReqeust::_internal_augend() const {
  return _impl_.augend_;
}
inline int64_t MathAddReqeust::augend() const {
  // @@protoc_insertion_point(field_get:MathAddReqeust.augend)
  return _internal_augend();
}
inline void MathAddReqeust::_internal_set_augend(int64_t value) {
  
  _impl_.augend_ = value;
}
inline void MathAddReqeust::set_augend(int64_t value) {
  _internal_set_augend(value);
  // @@protoc_insertion_point(field_set:MathAddReqeust.augend)
}

// int64 addend = 2;
inline void MathAddReqeust::clear_addend() {
  _impl_.addend_ = int64_t{0};
}
inline int64_t MathAddReqeust::_internal_addend() const {
  return _impl_.addend_;
}
inline int64_t MathAddReqeust::addend() const {
  // @@protoc_insertion_point(field_get:MathAddReqeust.addend)
  return _internal_addend();
}
inline void MathAddReqeust::_internal_set_addend(int64_t value) {
  
  _impl_.addend_ = value;
}
inline void MathAddReqeust::set_addend(int64_t value) {
  _internal_set_addend(value);
  // @@protoc_insertion_point(field_set:MathAddReqeust.addend)
}

// -------------------------------------------------------------------

// MathAddResponse

// int64 result = 1;
inline void MathAddResponse::clear_result() {
  _impl_.result_ = int64_t{0};
}
inline int64_t MathAddResponse::_internal_result() const {
  return _impl_.result_;
}
inline int64_t MathAddResponse::result() const {
  // @@protoc_insertion_point(field_get:MathAddResponse.result)
  return _internal_result();
}
inline void MathAddResponse::_internal_set_result(int64_t value) {
  
  _impl_.result_ = value;
}
inline void MathAddResponse::set_result(int64_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:MathAddResponse.result)
}

// -------------------------------------------------------------------

// MathSubReqeust

// int64 minuend = 1;
inline void MathSubReqeust::clear_minuend() {
  _impl_.minuend_ = int64_t{0};
}
inline int64_t MathSubReqeust::_internal_minuend() const {
  return _impl_.minuend_;
}
inline int64_t MathSubReqeust::minuend() const {
  // @@protoc_insertion_point(field_get:MathSubReqeust.minuend)
  return _internal_minuend();
}
inline void MathSubReqeust::_internal_set_minuend(int64_t value) {
  
  _impl_.minuend_ = value;
}
inline void MathSubReqeust::set_minuend(int64_t value) {
  _internal_set_minuend(value);
  // @@protoc_insertion_point(field_set:MathSubReqeust.minuend)
}

// int64 subtrahend = 2;
inline void MathSubReqeust::clear_subtrahend() {
  _impl_.subtrahend_ = int64_t{0};
}
inline int64_t MathSubReqeust::_internal_subtrahend() const {
  return _impl_.subtrahend_;
}
inline int64_t MathSubReqeust::subtrahend() const {
  // @@protoc_insertion_point(field_get:MathSubReqeust.subtrahend)
  return _internal_subtrahend();
}
inline void MathSubReqeust::_internal_set_subtrahend(int64_t value) {
  
  _impl_.subtrahend_ = value;
}
inline void MathSubReqeust::set_subtrahend(int64_t value) {
  _internal_set_subtrahend(value);
  // @@protoc_insertion_point(field_set:MathSubReqeust.subtrahend)
}

// -------------------------------------------------------------------

// MathSubResponse

// int64 result = 1;
inline void MathSubResponse::clear_result() {
  _impl_.result_ = int64_t{0};
}
inline int64_t MathSubResponse::_internal_result() const {
  return _impl_.result_;
}
inline int64_t MathSubResponse::result() const {
  // @@protoc_insertion_point(field_get:MathSubResponse.result)
  return _internal_result();
}
inline void MathSubResponse::_internal_set_result(int64_t value) {
  
  _impl_.result_ = value;
}
inline void MathSubResponse::set_result(int64_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:MathSubResponse.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_math_2eproto
