// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#include "math.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR MathAddRequest::MathAddRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.augend_)*/int64_t{0}
  , /*decltype(_impl_.addend_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathAddRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathAddRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathAddRequestDefaultTypeInternal() {}
  union {
    MathAddRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathAddRequestDefaultTypeInternal _MathAddRequest_default_instance_;
PROTOBUF_CONSTEXPR MathAddResponse::MathAddResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathAddResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathAddResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathAddResponseDefaultTypeInternal() {}
  union {
    MathAddResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathAddResponseDefaultTypeInternal _MathAddResponse_default_instance_;
PROTOBUF_CONSTEXPR MathSubRequest::MathSubRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.minuend_)*/int64_t{0}
  , /*decltype(_impl_.subtrahend_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathSubRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathSubRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathSubRequestDefaultTypeInternal() {}
  union {
    MathSubRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathSubRequestDefaultTypeInternal _MathSubRequest_default_instance_;
PROTOBUF_CONSTEXPR MathSubResponse::MathSubResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathSubResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathSubResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathSubResponseDefaultTypeInternal() {}
  union {
    MathSubResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathSubResponseDefaultTypeInternal _MathSubResponse_default_instance_;
static ::_pb::Metadata file_level_metadata_math_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_math_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_math_2eproto = nullptr;

const uint32_t TableStruct_math_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MathAddRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MathAddRequest, _impl_.augend_),
  PROTOBUF_FIELD_OFFSET(::MathAddRequest, _impl_.addend_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MathAddResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MathAddResponse, _impl_.result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MathSubRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MathSubRequest, _impl_.minuend_),
  PROTOBUF_FIELD_OFFSET(::MathSubRequest, _impl_.subtrahend_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MathSubResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MathSubResponse, _impl_.result_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MathAddRequest)},
  { 8, -1, -1, sizeof(::MathAddResponse)},
  { 15, -1, -1, sizeof(::MathSubRequest)},
  { 23, -1, -1, sizeof(::MathSubResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_MathAddRequest_default_instance_._instance,
  &::_MathAddResponse_default_instance_._instance,
  &::_MathSubRequest_default_instance_._instance,
  &::_MathSubResponse_default_instance_._instance,
};

const char descriptor_table_protodef_math_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nmath.proto\"0\n\016MathAddRequest\022\016\n\006augend"
  "\030\001 \001(\003\022\016\n\006addend\030\002 \001(\003\"!\n\017MathAddRespons"
  "e\022\016\n\006result\030\001 \001(\003\"5\n\016MathSubRequest\022\017\n\007m"
  "inuend\030\001 \001(\003\022\022\n\nsubtrahend\030\002 \001(\003\"!\n\017Math"
  "SubResponse\022\016\n\006result\030\001 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_math_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_math_2eproto = {
    false, false, 195, descriptor_table_protodef_math_2eproto,
    "math.proto",
    &descriptor_table_math_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_math_2eproto::offsets,
    file_level_metadata_math_2eproto, file_level_enum_descriptors_math_2eproto,
    file_level_service_descriptors_math_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_math_2eproto_getter() {
  return &descriptor_table_math_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_math_2eproto(&descriptor_table_math_2eproto);

// ===================================================================

class MathAddRequest::_Internal {
 public:
};

MathAddRequest::MathAddRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MathAddRequest)
}
MathAddRequest::MathAddRequest(const MathAddRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathAddRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.augend_){}
    , decltype(_impl_.addend_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.augend_, &from._impl_.augend_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.addend_) -
    reinterpret_cast<char*>(&_impl_.augend_)) + sizeof(_impl_.addend_));
  // @@protoc_insertion_point(copy_constructor:MathAddRequest)
}

inline void MathAddRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.augend_){int64_t{0}}
    , decltype(_impl_.addend_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathAddRequest::~MathAddRequest() {
  // @@protoc_insertion_point(destructor:MathAddRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathAddRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathAddRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathAddRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MathAddRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.augend_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.addend_) -
      reinterpret_cast<char*>(&_impl_.augend_)) + sizeof(_impl_.addend_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathAddRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 augend = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.augend_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 addend = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.addend_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathAddRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MathAddRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 augend = 1;
  if (this->_internal_augend() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_augend(), target);
  }

  // int64 addend = 2;
  if (this->_internal_addend() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_addend(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MathAddRequest)
  return target;
}

size_t MathAddRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MathAddRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 augend = 1;
  if (this->_internal_augend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_augend());
  }

  // int64 addend = 2;
  if (this->_internal_addend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_addend());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathAddRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathAddRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathAddRequest::GetClassData() const { return &_class_data_; }


void MathAddRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathAddRequest*>(&to_msg);
  auto& from = static_cast<const MathAddRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MathAddRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_augend() != 0) {
    _this->_internal_set_augend(from._internal_augend());
  }
  if (from._internal_addend() != 0) {
    _this->_internal_set_addend(from._internal_addend());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathAddRequest::CopyFrom(const MathAddRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MathAddRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathAddRequest::IsInitialized() const {
  return true;
}

void MathAddRequest::InternalSwap(MathAddRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MathAddRequest, _impl_.addend_)
      + sizeof(MathAddRequest::_impl_.addend_)
      - PROTOBUF_FIELD_OFFSET(MathAddRequest, _impl_.augend_)>(
          reinterpret_cast<char*>(&_impl_.augend_),
          reinterpret_cast<char*>(&other->_impl_.augend_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MathAddRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[0]);
}

// ===================================================================

class MathAddResponse::_Internal {
 public:
};

MathAddResponse::MathAddResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MathAddResponse)
}
MathAddResponse::MathAddResponse(const MathAddResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathAddResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:MathAddResponse)
}

inline void MathAddResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathAddResponse::~MathAddResponse() {
  // @@protoc_insertion_point(destructor:MathAddResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathAddResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathAddResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathAddResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MathAddResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathAddResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathAddResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MathAddResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MathAddResponse)
  return target;
}

size_t MathAddResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MathAddResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathAddResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathAddResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathAddResponse::GetClassData() const { return &_class_data_; }


void MathAddResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathAddResponse*>(&to_msg);
  auto& from = static_cast<const MathAddResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MathAddResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathAddResponse::CopyFrom(const MathAddResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MathAddResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathAddResponse::IsInitialized() const {
  return true;
}

void MathAddResponse::InternalSwap(MathAddResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MathAddResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[1]);
}

// ===================================================================

class MathSubRequest::_Internal {
 public:
};

MathSubRequest::MathSubRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MathSubRequest)
}
MathSubRequest::MathSubRequest(const MathSubRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathSubRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.minuend_){}
    , decltype(_impl_.subtrahend_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.minuend_, &from._impl_.minuend_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.subtrahend_) -
    reinterpret_cast<char*>(&_impl_.minuend_)) + sizeof(_impl_.subtrahend_));
  // @@protoc_insertion_point(copy_constructor:MathSubRequest)
}

inline void MathSubRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.minuend_){int64_t{0}}
    , decltype(_impl_.subtrahend_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathSubRequest::~MathSubRequest() {
  // @@protoc_insertion_point(destructor:MathSubRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathSubRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathSubRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathSubRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MathSubRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.minuend_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.subtrahend_) -
      reinterpret_cast<char*>(&_impl_.minuend_)) + sizeof(_impl_.subtrahend_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathSubRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 minuend = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.minuend_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 subtrahend = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.subtrahend_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathSubRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MathSubRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 minuend = 1;
  if (this->_internal_minuend() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_minuend(), target);
  }

  // int64 subtrahend = 2;
  if (this->_internal_subtrahend() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_subtrahend(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MathSubRequest)
  return target;
}

size_t MathSubRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MathSubRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 minuend = 1;
  if (this->_internal_minuend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_minuend());
  }

  // int64 subtrahend = 2;
  if (this->_internal_subtrahend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_subtrahend());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathSubRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathSubRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathSubRequest::GetClassData() const { return &_class_data_; }


void MathSubRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathSubRequest*>(&to_msg);
  auto& from = static_cast<const MathSubRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MathSubRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_minuend() != 0) {
    _this->_internal_set_minuend(from._internal_minuend());
  }
  if (from._internal_subtrahend() != 0) {
    _this->_internal_set_subtrahend(from._internal_subtrahend());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathSubRequest::CopyFrom(const MathSubRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MathSubRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathSubRequest::IsInitialized() const {
  return true;
}

void MathSubRequest::InternalSwap(MathSubRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MathSubRequest, _impl_.subtrahend_)
      + sizeof(MathSubRequest::_impl_.subtrahend_)
      - PROTOBUF_FIELD_OFFSET(MathSubRequest, _impl_.minuend_)>(
          reinterpret_cast<char*>(&_impl_.minuend_),
          reinterpret_cast<char*>(&other->_impl_.minuend_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MathSubRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[2]);
}

// ===================================================================

class MathSubResponse::_Internal {
 public:
};

MathSubResponse::MathSubResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MathSubResponse)
}
MathSubResponse::MathSubResponse(const MathSubResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathSubResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:MathSubResponse)
}

inline void MathSubResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathSubResponse::~MathSubResponse() {
  // @@protoc_insertion_point(destructor:MathSubResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathSubResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathSubResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathSubResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MathSubResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathSubResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathSubResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MathSubResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MathSubResponse)
  return target;
}

size_t MathSubResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MathSubResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathSubResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathSubResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathSubResponse::GetClassData() const { return &_class_data_; }


void MathSubResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathSubResponse*>(&to_msg);
  auto& from = static_cast<const MathSubResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MathSubResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathSubResponse::CopyFrom(const MathSubResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MathSubResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathSubResponse::IsInitialized() const {
  return true;
}

void MathSubResponse::InternalSwap(MathSubResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MathSubResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MathAddRequest*
Arena::CreateMaybeMessage< ::MathAddRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MathAddRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::MathAddResponse*
Arena::CreateMaybeMessage< ::MathAddResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MathAddResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::MathSubRequest*
Arena::CreateMaybeMessage< ::MathSubRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MathSubRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::MathSubResponse*
Arena::CreateMaybeMessage< ::MathSubResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MathSubResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
